AWSTemplateFormatVersion: '2010-09-09'
Description: Fargate deployment for battle-hexes-api

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  EcrImage:
    Type: String
    Description: Full image URI

Resources:

  BattleHexesCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: battle-hexes-dev-cluster

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: battle-hexes-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP to ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  BattleHexesSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP from ALB to ECS
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup

  BattleHexesLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: battle-hexes-alb
      Scheme: internet-facing
      Type: application
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup

  BattleHexesTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: battle-hexes-api-tg
      Port: 8000
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /

  BattleHexesListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref BattleHexesLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref BattleHexesTargetGroup

  BattleHexesTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: battle-hexes-api-task
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: battle-hexes-api
          Image: !Ref EcrImage
          PortMappings:
            - ContainerPort: 8000

  BattleHexesService:
    Type: AWS::ECS::Service
    DependsOn: BattleHexesListener
    Properties:
      Cluster: !Ref BattleHexesCluster
      DesiredCount: 1
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: battle-hexes-api
          ContainerPort: 8000
          TargetGroupArn: !Ref BattleHexesTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref BattleHexesSecurityGroup
      TaskDefinition: !Ref BattleHexesTaskDefinition

Outputs:
  PublicClusterName:
    Description: ECS Cluster name
    Value: !Ref BattleHexesCluster
