AWSTemplateFormatVersion: '2010-09-09'
Description: Static website hosting for Battle Hexes web project
Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket to host the website
  AcmCertificateArn:
    Type: String
    Description: ACM certificate ARN in us-east-1 for the web domain
  HostedZoneId:
    Type: String
    Description: Public hosted zone ID for battlehexes.com
  WebDomainName:
    Type: String
    Default: dev.battlehexes.com
    Description: Public DNS name for this environment
    AllowedPattern: '^[a-z0-9.-]+$'

Conditions:
  HasAlias: !Not [!Equals [!Ref WebDomainName, ""]]

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
    DeletionPolicy: Retain
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${WebsiteBucket.Arn}/*'
  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases: !If [HasAlias, [!Ref WebDomainName], !Ref "AWS::NoValue"]
        Origins:
          - Id: WebsiteOrigin
            DomainName: !Sub "${WebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only  # because S3 static website endpoints don't support HTTPS
        DefaultCacheBehavior:
          TargetOriginId: WebsiteOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 31536000
        CacheBehaviors:
          - PathPattern: 'index.html'
            TargetOriginId: WebsiteOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            Compress: true
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            DefaultTTL: 0
            MinTTL: 0
            MaxTTL: 0
        PriceClass: PriceClass_100  # Cheapest CDN tier
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  WebsiteAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref WebDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt WebsiteDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2     # CloudFront’s global hosted zone ID
        EvaluateTargetHealth: false

Outputs:
  BucketName:
    Description: Name of the website bucket
    Value: !Ref WebsiteBucket
  WebsiteURL:
    Description: URL for website hosted on S3
    Value: !GetAtt WebsiteBucket.WebsiteURL
  CloudFrontURL:
    Description: "CloudFront distribution URL"
    Value: !Sub "https://${WebsiteDistribution.DomainName}"
  WebUrl:
    Description: Public URL for the website
    Value: !Sub "https://${WebDomainName}"
