name: Test Python API

on:
  push:
    paths:
      - 'battle-hexes-api/**'
      - 'battle-hexes-core/**'
      - 'battle-agent-random/**'
      - 'battle-agent-rl/**'
      - 'api-checks.sh'
      - '.github/workflows/api-test.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r battle-hexes-api/requirements.txt
          pip install -r battle-hexes-api/requirements-test.txt

      - name: Run checks
        run: ./api-checks.sh
