name: Deploy Dev DynamoDB

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # for OIDC to assume role
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (assume deploy role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation stack
        run: |
          set -euo pipefail
          export TABLE_NAME="battle-hexes-dev"

          if aws dynamodb describe-table --table-name "$TABLE_NAME" >/dev/null 2>&1; then
            MANAGE=false
          else
            MANAGE=true
          fi

          aws cloudformation deploy \
            --template-file "battle_hexes_api/dev-database.yml" \
            --stack-name battle-hexes-dev-data \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              TableName="$TABLE_NAME" \
              ManageTable="$MANAGE" \
              EnableStreams=false \
              StreamViewType="NEW_AND_OLD_IMAGES"

      - name: Enable termination protection
        run: |
          aws cloudformation update-termination-protection \
            --stack-name "battle-hexes-dev-data" \
            --enable-termination-protection

      - name: Show stack outputs
        run: |
          aws cloudformation describe-stacks --stack-name "battle-hexes-dev-data" \
            --query "Stacks[0].Outputs" --output table
