name: Deploy Web Project

on:
  workflow_dispatch:

permissions:
  id-token: write  # ✅ Required for OIDC
  contents: read   # ✅ Required for `actions/checkout`

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: battle-hexes-web
        run: npm install

      - name: Build
        working-directory: battle-hexes-web
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # TODO debugging step to verify AWS credentials
      - name: Check AWS identity
        run: aws sts get-caller-identity

      - name: Deploy placeholder
        run: echo "Deploy step not implemented"
