name: Deploy Web Project

on:
  workflow_dispatch:

permissions:
  id-token: write  # ✅ Required for OIDC
  contents: read   # ✅ Required for `actions/checkout`

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: battle-hexes-web
        run: npm install

      - name: Build
        working-directory: battle-hexes-web
        run: npm run build:dev

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy infrastructure
        env:
          BUCKET_NAME: ${{ secrets.WEB_BUCKET_NAME }}
          ACM_CERT_ARN: ${{ secrets.ACM_CERT_ARN }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
        run: |
          aws cloudformation deploy \
            --stack-name battle-hexes-web \
            --template-file battle-hexes-web/cloudformation-template.yml \
            --parameter-overrides \
              BucketName=$BUCKET_NAME \
              AcmCertificateArn=$ACM_CERT_ARN \
              HostedZoneId=$HOSTED_ZONE_ID \
              WebDomainName=dev.battlehexes.com \
            --no-fail-on-empty-changeset

      - name: Sync build artifacts
        env:
          BUCKET_NAME: ${{ secrets.WEB_BUCKET_NAME }}
        run: |
          aws s3 sync battle-hexes-web/dist s3://$BUCKET_NAME \
            --exclude "index.html" \
            --cache-control "public, max-age=31536000, immutable" \
            --delete
          aws s3 cp battle-hexes-web/dist/index.html s3://$BUCKET_NAME/index.html \
            --cache-control "no-cache, max-age=0, must-revalidate"

      - name: Show stack outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name battle-hexes-web \
            --query "Stacks[0].Outputs" \
            --output table
